name: Storybook

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deloy:
    if: ${{ github.event_name != 'pull_request' || (github.event_name == 'pull_request' && !github.event.pull_request.draft) }}
    runs-on: ubuntu-latest
    timeout-minutes: 4

    steps:
      - name: Checkout PR
        uses: actions/checkout@v2

      - name: Use Node.js 15
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build
        run: npm run build:storybook

      - name: Deploy
        id: deploy-storybook
        if: github.event_name == 'pull_request'
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-comment: false
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          working-directory: .storybook

      - name: Comment
        if: github.event_name == 'pull_request'
        uses: NejcZdovc/comment-pr@v1
        with:
          file: 'comment_storybook.md'
          identifier: 'GITHUB_ACTION_COMMENT_DEMO'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          URL: ${{steps.deploy-storybook.outputs.preview-url}}
